// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xujdpgopnrziyvzrglpk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1amRwZ29wbnJ6aXl2enJnbHBrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NzcyMTksImV4cCI6MjA3MTQ1MzIxOX0.0Eqc3lmluIWlziuseqRrwDKKziHB_rZEcBmsTXILmzA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});